Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/experiments/entropy_estimation_study.py", line 203, in <module>
    args.func(args)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/experiments/entropy_estimation_study.py", line 58, in generate_universe
    universe_model_wrapper.fit(X, y)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/src/utils/models.py", line 96, in fit
    self.model.fit(X_train, y_train)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/.RAL/lib64/python3.9/site-packages/sklearn/base.py", line 1389, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/.RAL/lib64/python3.9/site-packages/sklearn/ensemble/_forest.py", line 419, in fit
    y, expanded_class_weight = self._validate_y_class_weight(y)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/.RAL/lib64/python3.9/site-packages/sklearn/ensemble/_forest.py", line 831, in _validate_y_class_weight
    check_classification_targets(y)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/.RAL/lib64/python3.9/site-packages/sklearn/utils/multiclass.py", line 222, in check_classification_targets
    raise ValueError(
ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/experiments/entropy_estimation_study.py", line 203, in <module>
    args.func(args)
  File "/mnt/beegfs/homes/simondn/RashomonActiveLearning/experiments/entropy_estimation_study.py", line 105, in analyze_universe
    raise FileNotFoundError(f"Universe data file not found: {universe_file}. Please run the 'generate' mode first.")
FileNotFoundError: Universe data file not found: /mnt/beegfs/homes/simondn/RashomonActiveLearning/results/entropy_study/Auto_universe_data.pkl. Please run the 'generate' mode first.
